export const LOGGIN_SUCCESS = 'LOGGIN_SUCCESS';
export const LOGGIN_ERROR = 'LOGGIN_ERROR';
export const EXPENSES_LOAD_SUCCESS = 'EXPENSES_LOAD_SUCCESS';
export const EXPENSES_LOAD_ERROR = 'EXPENSES_LOAD_ERROR';
